-- Supabase SQL Schema for PrimeTemp Mail Bot
-- Run this in your Supabase SQL Editor: Dashboard -> SQL Editor -> New Query

CREATE TABLE IF NOT EXISTS public.users (
    telegram_id bigint PRIMARY KEY,
    active_email text,
    language text DEFAULT 'bn',
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id bigint,
    email text NOT NULL,
    password text NOT NULL,
    token text,
    account_id text,
    last_msg_id text,
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE(telegram_id, email)
);

-- Enable RLS and Grant Access
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public anon access to users" ON public.users FOR ALL USING (true);
CREATE POLICY "Allow public anon access to accounts" ON public.accounts FOR ALL USING (true);
